### ISSUE TITLE
Some Advice on Traversal Algorithm

### ISSUE THREAD

**Issue by duangsuse** [BaseMax/MatlabMatrixProject#1]
[In reply to duangsuse::Echo](https://t.me/dsuse/10203)
可是，即使是线性查找也有点奇怪呢？... 不清楚呢

https://github.com/BaseMax/MatlabMatrixProject/blob/master/BiggestValueMatrix.m#L8
`maximum=Matrix(1,1);`

反正要被替换，为什么不直接随便初始化个简单的...

https://github.com/BaseMax/MatlabMatrixProject/blob/master/BiggestValueMatrix.m#L10
`for i=1:rows`

没有考虑到 Matrix 为 0x~ 维度的情况

https://github.com/BaseMax/MatlabMatrixProject/blob/master/BiggestValueMatrix.m#L12
`if maximum <= Matrix(i,j);`
其实等于的时候不必替换

https://github.com/BaseMax/MatlabMatrixProject/blob/master/BiggestValueMatrix.m#L17
`[row_max column_max] = find(A == maximum);`
别这样，扫描一遍已经够了，为啥要再来第二遍...

Matlab 已经很不怎么优化了（所谓的『数据处理语言』，我个人觉得还不如直接 Julia），还这样一遍一遍找 O(n) 两遍... 尽可能一次弄完吧

类似 #Haskell #fp 的 banana split:

```haskell
length = foldl (\x y -> succ y) 1
product = foldl (*) 1

productLength = foldl ( \(a0, a1) x -> (x * a0, succ a1) ) (1, 1)
productLength' xs = (product xs, length xs)
```

`productLength` 比 `productLength'` 要好，它只 travelse 了一遍，没有不必要地再去算第二遭

**Comment by BaseMax** [comment]
Hi @duangsuse,
Thanks you.

But it was a sample code for university question.
and code should be clear for the my new student. (They not have experience in programming)
any way, i will fix and improve it.
You can send pull for it, if you like to improve...

Best Regards,
Max.

**Comment by duangsuse** [comment]
> Hi @duangsuse,
> Thanks you.
> 
> But _it was a sample code for university question._
> and code should be clear for the starter student.
> any way, i will fix and improve it.
> You can send pull for it, if you like to improve...
> 
> Best Regards,
> Max.

In that case, I'll take your explanation.

Have a nice day and thanks for your quick reply. @BaseMax
